# Docker Compose version 3.8
services:
  # Node.js Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: brainity-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - brainity-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get(`http://localhost:${process.env.PORT}/`, (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: brainity-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - brainity-network
    env_file:
      - ./client/.env

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: brainity-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - brainity-network

networks:
  brainity-network:
    driver: bridge
